export function getDocumentation(opts: { libraryName: string; }) {
    return `/*
Automatically generated code. DO NOT edit this file!

To use, ensure the following:

1. That this code is copied into the application that is going to communicate with the server.
2. That ${opts.libraryName} is added as a dependency in the client application. Install it by running:

   npm install --save ${opts.libraryName}
*/
`;
}
