export function getDocumentation(opts: { libraryName: string; }) {
    return "" +
`/*
Automatically generated code. Do not edit this file.

To use, ensure the following:

1. That this code is copied into the application that is going to communicate with the server.
2. That ${opts.libraryName} is added as a dependency in the application. Install it by running:

   npm install --save ${opts.libraryName}

3. If necessary, include the typescript definition file for ${opts.libraryName} in your application.

4. That the import paths in this file are correct. If they aren't, change the code
    generation script to generate the correct paths.
*/
`;
}
